sudo: false
language: ruby
rvm:
- 2.5.3
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --check-html --check-img-http --check-opengraph --assume-extension || true
deploy:
  provider: script
  skip_cleanup: true
  script:  sh .ci/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts:
  - "$SSH_HOST"
  apt:
    packages:
    - sshpass
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: ibotty
  - EMAIL: travis@ibotty.net
  - secure: "iXDSynWh1R08zSTdj5kqjURmQjbVuS8LMJ5YlT+SJXzy/jKWXyZ5KqTvUHHUXG1cHM5xxB5mA+pSWdFPPMReYSp31jC2/cn1B7EF05Z8eB5QJ3vmGMOBz/oCyQQVXpkQf6qdeOnKESMl8Kx/ff8wUoZyUdksm6hHQO4QMnhzCdnULsen1kQoq7G1vIBxzpxZ5Ztd7Q7ZsGJYonVUiGaOwFMkAg8hevI20984teUcAJE8NjqRhel9tCF7tMOOWo2qUwZUkb1Y/D20OAgPSgSfyK9HYhNaLMQITz48boGmqJmT1PwPVfIIhk/BQTXoWJlAN8PooCklAqwzJEbb+FuhLMPUcDSq7mnUOPOMi6Zvio+6zCE/lGbyO18nv8aSVBqQKP2gw67Xf12NmsESO6WdgojNoA1hSQctzAsoPKMtgZWaxcBQduRQnU7wkt5aM31JWlW130Wk8EA3Cw9g1hA4oxzeiT6y8gdBERPIH49FNtjp/aNjxIKlkn1t3vVcreRAzCuwDOlKONilcNyjhCt5r4C0/mmRlP1kdsOYF+BXeWRPRkNHj+/tgzJWb/mH9qLhvd0San1/hM13KOqIgGhQoFJVCBKJfrsYt5Kbv8kgcjPg1Eqfs62u2xdIvVSj2iOx5NHrGGGPkU1D9ej5HAbvyGGFM5kXnIWJ0DqYHJ4NB/k="
  - secure: "uD/TwEJIMrh8Vv6dHRTswOOo5i5Q7Nb78F/aqEmQ5WlY2P0lHU+h9HthxFSAECPLb/hFY79zZYC/baA7TRZEgozvJUA5DNzz7hq55tec5YyD5MEfK3UxSyZGtHg+WZkkhbsLh8dJCjfuDIciVDr6/upDqleSXW4Jw4Eyw6lz4WNQfgVMVLpoTLxXwcfIL5ywAXTYBuhJQdedxT6XFIDqtJ6nU/QRPihiQkexEARqCdehIPWTSzFW8UThEaL4wHKrSjKYs2g4ueGouA3TgUMsGyITyvx8RuewMGfgI7uaQsHRrc9zuOvJ8YTzRfCOXM1ta4mzN8tQ5JhYIfhbpz2Rn3haM7Yo2RNZtVujPGHwwH81kplY9ejEBvrT5QwXb2TLw9pxRVA86SOShWR+bszgIb6Gz3SJXU+5bHa6ebSqNbUtF+/+/U4q46rvq7ANpp/7E0b4VMbRFsGJq8HTqBzRqjVTjrtdv2OvwICjnoHSbd29FQJz7KYILfsNSXpatN8EfHUPhIMBj2HH8LXDeS3HajIGxlOTJMxJLYclxU8o3NDxfFV9P7gevYlhHozvAAmqvF51iB/jtmTmQMqlQ4OzfS1OYDMnaxBMEf06CwwvmNIjaT8aSfWDWlSGTuL3COnEzrOJ4S2Zino2bjetertqkN7dSYcHPQOM5cd6bnufDvk="
  - secure: "IcxKnOif56q976yvpve9p5up19oV4HIRTQXNwXai5/+h1r4gh4G6D1yAU3corDqb4YM1fdYT1O3dn5Xsr7GlQVe6omVEhy+rHZldaNuqhAbhRPxrr0tbfmIrCP0+IAaWXYVAx0DPDvToEif4Ty1u64hjNux0O2fvUOuhtYcwAUX7EZwSFOM3slN4wUsEjAtV2XV7ZSwZfYfseh+BdWj4V3Yh/FO++OQa6bsYSU0GXRa2yGWlWc7SAalqDfXzqbXyTlSGucqYQIBYcgcH1KWfn3rjduwVaok+LGrTJU2vdl6G+5IPY6CPX9MY2VkrBqQENv3RM06BA9yyoykgsbQSXJt9cf8K+X0mE0j7mK9LgbfhNP5cD7risD19ePmhRf+qZIbVxyWZZHKNzSWBdMqZbYHq4/f4/QWZ8qzpZYnVP+DH+86p0/xrep1IOBOymy63wvJlE5Zd9+5BwO2492Z2fwf9+NW9iZ0jamLPCCvRsG99yE0bBCvszoHIM/RJhCe3RYoTotszqE5f574N7vo69PaFjipxonnv7PcoCbe33+JntVdHaS/ViN1SPbrEU62l1lpDBQqrE4LqnZhx/sl2N1XVnSGIngTeEpWM4PVn/KjW5135txA+IimlLc3jval83aEde4u3zM9X+9j72MiE34fxLHi5pnTefdqxPwiZZYI="
